name: Release from main
on:
  push:
    branches:
      - main
      
jobs:
  setup-workflow:
    uses: ./.github/workflows/setup.yml
  
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:  
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: ./module