name: Build module for production
on: 
  push:
    branches:
      - main
jobs:
  build-prod:
    needs: setup-and-cache-node-module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      
      - name: build-prod
        run: (cd module && npm run build)