name: Setup and cache Node for Module

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Build
        id: build
        run: |
          (cd ~/.npm && ls -la)
          (cd ../ && ls -la)
          ls -la
          npm run build
        working-directory: ./module