name: Lint & Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-npm
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set Node.js 14.16.1
        uses: actions/setup-node@master
        with:
          node-version: 14.16.1

      - name: npm install
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm i

      - name: lint
        run: (cd module && npm run lint)
      
      - name: build
        run: (cd module && npm run build)

      - name: artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: modules/dist