# .github/workflows/chromatic.yml

name: 'Chromatic'

on:
  push:
    branches:
      - main
      - develop

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm i

      - name: Publish to Chromatic
        uses: chromaui/action@v1

        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          buildScriptName: npm build-storybook
          working-directory: ./module
        env: 
          CHROMATIC_RETRIES: 3