name: Release from main
on: workflow_call

jobs:
  release-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@latest
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Download build artifact
        uses: actions/download-artifact@latest
        with:
          name: build-artifact
          path: ${{ github.workspace }}/module/dist

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: ./module