name: Lint module
on: workflow_call
jobs:
  lint-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Rebuild native dependencies
        run: pnpm rebuild unrs-resolver
        working-directory: ./module

      - name: Run linting
        run: pnpm lint && pnpm stylelint
        working-directory: ./module
