name: Setup and cache Node for Module

on: workflow_call

jobs:
  setup-and-cache-node-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/install-node-and-pnpm