name: Test

on: workflow_call

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run Jest Tests
        run: pnpm test-ci
        working-directory: ./module

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
        working-directory: ./storybook

      - name: Build Armstrong & Storybook
        run: pnpm install && pnpm build-storybook
        working-directory: ./storybook

      - name: Serve Storybook and run tests
        run: pnpm test-storybook-ci
        working-directory: ./storybook
