name: Lint module
on: workflow_call
jobs:
  lint-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
        #   ref: ${{ github.event.workflow_run.head_branch }}

      - uses: ./.github/actions/install-node-and-pnpm

      - name: Run linting
        run: pnpm lint && pnpm stylelint
        working-directory: ./module