name: Pages
on: workflow_call

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build Storybook
        run: (cd module && npm run build && cd ../storybook && npm run build-storybook)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook/storybook-static