# .github/workflows/chromatic.yml

name: 'Chromatic'

on: workflow_call

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-node-and-pnpm

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          buildScriptName: build-storybook
          workingDir: ./storybook
          exitOnceUploaded: true
        env:
          CHROMATIC_RETRIES: 3