name: Build

on: workflow_call

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: ./.github/actions/install-node-and-pnpm

      - name: Build
        id: build
        run: npm run build
        working-directory: ./module

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}/module/dist
          retention-days: 5