# .github/workflows/chromatic.yml

name: 'Chromatic'

on: workflow_call

jobs:
  setup:
    uses: ./.github/workflows/job_setup.yml

  chromatic-deployment:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@v5
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install storybook node modules
        id: storybook-node-modules
        run: pnpm install
        working-directory: ./storybook

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          buildScriptName: build-storybook
          workingDir: ./storybook
          exitOnceUploaded: true
        env:
          CHROMATIC_RETRIES: 3
