name: Pages
on: workflow_call

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: ./.github/actions/install-node-and-pnpm

      - name: Build Storybook
        run: (cd module && pnpm build && cd ../storybook && pnpm build-storybook)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook/storybook-static