name: Setup and cache Node for Module

on: workflow_call

jobs:
  setup-and-cache-node-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set Node.js to current version and cache in module
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: Cache node modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install root node dependencies
        if: ${{ steps.node-modules.outputs.cache-hit != 'true' }}
        id: install-root-node-dependencies
        run: npm ci --legacy-peer-deps

      - name: Install module node dependencies
        if: ${{ steps.node-modules.outputs.cache-hit != 'true' }}
        id: install-module-node-dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./module

      - name: Install storybook node dependencies
        if: ${{ steps.node-modules.outputs.cache-hit != 'true' }}
        id: install-storybook-node-dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./storybook
