name: Release from main
on: workflow_call

jobs:
  release-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          registry-url: "https://registry.npmjs.org"
          token: ""

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/module/node_modules
            ${{ github.workspace }}/storybook/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ${{ github.workspace }}/module/dist

      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
        working-directory: ./module
