name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 14.16.1
        uses: actions/setup-node@master
        with:
          node-version: 14.16.1

      - name: npm install and lint
        run: cd module && npm i && npm run lint
