name: Pull Request

on: push

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  
  build:
    needs: [setup]
    uses: ./.github/workflows/build.yml

  test: 
    needs: [setup, build]
    uses: ./.github/workflows/test.yml