name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set Node.js version and cache
        uses: actions/setup-node@master
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: "module/package-lock.json"
      - name: Install dependencies
        run: npm ci
        working-directory: ./module
      - name: build
        run: npm run build
        working-directory: ./module
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        working-directory: ./module