name: Setup and cache Node for Module
on: workflow_call

jobs: 
  setup-and-cache-node-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set Node.js to current version and cache in module
        id: setup-node
        uses: actions/setup-node@master
        with:
          node-version-file: '.tool-versions'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install node dependencies
        if: ${{ steps.setup-node.outputs.cache-hit != 'true' }}
        id: install-node-dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./module
    
      - name: Build
        id: build
        run: npm run build
        working-directory: ./module
      
      - name: Upload node modules artifact
        id: node-modules-artifact
        uses: actions/upload-artifact@master
        with: 
          name: node-modules
          path: ./module/node_modules/