name: Setup and cache Node for Module
on: workflow_call
jobs: 
  setup-and-cache-node-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set Node.js to current version and cache in module
        id: setup-node
        uses: actions/setup-node@master
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: |
            module/package-lock.json
            package-lock.json
      - run: npm ci
      
      - if: ${{ steps.npm.outputs.cache-hit != 'true' }}
        name: Install node dependencies in module
        id: install-node-dependencies-module
        run: npm i
        working-directory: |
          module
          .