name: Setup and cache Node for Module
on: workflow_call

jobs: 
  setup-and-cache-node-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set Node.js to current version and cache in module
        id: setup-node
        uses: actions/setup-node@master
        with:
          node-version-file: '.tool-versions'

      - name: Cache npm packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: ~/.npm        
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install node dependencies
        if: ${{ steps.npm.outputs.cache-hit != 'true' }}
        id: install-node-dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./module