name: Test
on: [pull_request]
env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  
jobs:
  test:
    runs-on: ubuntu-latest
    needs: setup-workflow
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Download node modules artifact
        id: download-node-modules
        uses: actions/download-artifact@master
        with: 
          name: node-modules
          path: ./module/node_modules

      - name: Run Jest Tests
        run: npm run test-ci
        working-directory: ./module

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Armstrong & Storybook
        run: npm run build-storybook
        working-directory: ./module

      - name: Serve Storybook and run tests
        run: npm run test-storybook-ci
        working-directory: ./module
