name: Test
on: [pull_request]
env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set Node.js to current version and cache in module
        id: set-node-and-cache-module
        uses: actions/setup-node@master
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: "module/package-lock.json"

      - name: Install Dependencies
        run: (cd module && npm ci --legacy-peer-deps)

      - name: Run Jest Tests
        run: (cd module && npm run test-ci)

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Armstrong & Storybook
        run: (cd module && npm run build && npm run build-storybook)

      - name: Serve Storybook and run tests
        run: (cd module && npm run test-storybook-ci)

      - name: Set Node.js to current version and cache in module-new
        id: set-node-and-cache-module-new
        uses: actions/setup-node@master
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: "module-new/package-lock.json"

      - name: Install Dependencies in module-new
        run: (cd module-new && npm ci --legacy-peer-deps)

      - name: Run Jest Tests in module-new
        run: (cd module-new && npm run test-ci)

      - name: Build Armstrong & Storybook in module-new
        run: (cd module-new && npm run build && npm run build-storybook)

      - name: Serve Storybook and run tests in module-new
        run: (cd module-new && npm run test-storybook-ci)
