name: Test
on: pull_request
env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144
  
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
    
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build project'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Restore node modules cache
        id: node-modules
        uses: actions/cache/restore@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          
      - name: Run Jest Tests
        run: npm run test-ci
        working-directory: ./module

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Armstrong & Storybook
        run: npm run build-storybook
        working-directory: ./module

      - name: Serve Storybook and run tests
        run: npm run test-storybook-ci
        working-directory: ./module
