name: Pull Request

on: push

jobs:
  setup:
    uses: ./.github/workflows/job_setup.yml

  build:
    needs: [setup]
    uses: ./.github/workflows/job_build.yml

  lint:
    needs: [setup, build]
    uses: ./.github/workflows/job_lint.yml

  test:
    needs: [setup, build]
    uses: ./.github/workflows/job_test.yml
