name: Push

on:
  push:
    branches-ignore:
      - main
      - alpha

jobs:
  setup:
    uses: ./.github/workflows/job_setup.yml

  build:
    needs: [setup]
    uses: ./.github/workflows/job_build.yml

  lint:
    needs: [setup, build]
    uses: ./.github/workflows/job_lint.yml

  test:
    needs: [setup, build]
    uses: ./.github/workflows/job_test.yml

  chromatic:
    needs: [setup, build, lint, test]
    uses: ./.github/workflows/job_chromatic.yml
    secrets: inherit
